config:
    to_email: info@example.com
    to_subject: ［株式会社テスト］お問い合わせ
    auto_reply_subject: ［株式会社テスト］お問い合わせありがとうございます
    auto_reply_name: 株式会社テスト
    google_client_id: {クライアント ID}
    google_client_email: {メールアドレス}
    google_client_key: {P12 ファイルのファイル名}
    google_client_key_password: notasecret
